x-env-vars:
  # Общие переменные окружения для всех сервисов
  &common-env-vars
  OPCUA_MAIN_SERVER: "opc.tcp://opcua-server:4840/freeopcua/server/"
  OPCUA_MAIN_NAMESPACE: "namespace_1"

  # Добавлены переменные для резервного сервера
  OPCUA_BACKUP_SERVER: "opc.tcp://opcua-backup-server:4840/freeopcua/server/"
  OPCUA_BACKUP_NAMESPACE: "namespace_1"

services:
  opcua-server:
    image: opcua-server:latest
    build:
      context: .
      dockerfile: opcua_server/Dockerfile
    restart: unless-stopped
    environment: *common-env-vars
    networks:
      - default
    ports:
      - '4840:4840'

  opcua-model:
    image: opcua-model:latest
    build:
      context: .
      dockerfile: opcua_model/Dockerfile
    restart: unless-stopped
    environment: *common-env-vars
    networks:
      - default

  main-controller-1:
    image: opcua-controller:latest
    build:
      context: .
      dockerfile: opcua_controller/controller_1/main_controller/Dockerfile
    restart: unless-stopped
    environment: *common-env-vars
    networks:
      - default

  # backup-controller-1:
  #   image: opcua-controller:latest
  #   build:
  #     context: .
  #     dockerfile: opcua_controller/controller_1/backup_controller/Dockerfile
  #   restart: unless-stopped
  #   environment:
  #     <<: *common-env-vars
  #     OPCUA_BACKUP_SERVER: ${OPCUA_BACKUP_SERVER}
  #     OPCUA_BACKUP_NAMESPACE: ${OPCUA_BACKUP_NAMESPACE}
  #   networks:
  #     - default

  watchdog_service:
    image: watchdog-service:latest
    build:
      context: .
      dockerfile: watchdog_service/Dockerfile
    restart: unless-stopped
    environment: *common-env-vars
    networks:
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Добавлено для доступа к Docker
    container_name: watchdog-service

  api_server:
    image: api-server:latest
    build:
      context: .
      dockerfile: api_server/Dockerfile
    restart: unless-stopped
    environment: *common-env-vars
    networks:
      - default
    ports:
      - '8000:8000' # Порт для доступа к API-серверу
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Добавлено для доступа к Docker

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
